### ISSUE TITLE
[播放窗口] 弹出错误提示: Uncaught Exception: TypeError: Cannot read properties of undefined (reading 'width')

### ISSUE THREAD

**Issue by mf1389004071** [Hiram-Wong/ZyPlayer#322]
### zyplayer 版本

3.3.7

### 重现步骤

1. 电脑环境(MacBookPro11,4; 系统版本12.7.6 (21H1320); inter芯片) 
2. 打开软件
3. 点击任何影视资源, 进入播放窗口
4. 都会提示此错误, 导致永远无法打开最终的播放窗口

### 报错信息

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'width')
at createPlay (/Applications/zyplayer.app/Contents/Resources/app.asar/out/main/index.js:22163:36)
at IpcMainImpl.<anonymous> (/Applications/zyplayer.app/Contents/Resources/app.asar/out/main/index.js:22431:9)
at IpcMainImpl.emit (node:events:513:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81099)
at EventEmitter.emit (node:events:513:28)

实际截图如下
<img width="357" alt="image" src="https://github.com/user-attachments/assets/c883fc26-af8e-4a27-b054-0abc9aa93636">

### 期望结果

可正常通过播放窗口观看查询到的影视剧

### 实际结果

一直弹出报错信息, 然后无法打开播放窗口, 无法观看影视剧

### 系统信息

电脑环境(MacBookPro11,4; 系统版本12.7.6 (21H1320); inter芯片)

**Comment by Hiram-Wong** [comment]
该问题由于数据库数据没有按照要求导致，查看历史issue有解决方案
