### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by dai19470** [Hiram-Wong/ZyPlayer#330]
### zyplayer 版本

v3.3.7

### 重现步骤

1. yarn install build:web 
2.  upload in tomcat/webapps 
3.  sh startup.sh
4. get error

### 报错信息

vendor_DmporkZp.js:2154 
 TypeError: Cannot read properties of undefined (reading 'ipcRenderer')
    at setup (indexCu15VNeD.js:227:21)
    at callWithErrorHandling (vendor_DmporkZp.js:2096:19)
    at setupStatefulComponent (vendor_DmporkZp.js:8265:25)
    at setupComponent (vendor_DmporkZp.js:8252:36)
    at mountComponent (vendor_DmporkZp.js:5938:7)
    at processComponent (vendor_DmporkZp.js:5914:9)
    at patch (vendor_DmporkZp.js:5475:11)
    at render26 (vendor_DmporkZp.js:6614:7)
    at mount (vendor_DmporkZp.js:4965:13)
    at app2.mount (vendor_DmporkZp.js:10118:19)

### 系统信息

linux

### 补充说明

<img width="854" alt="Snipaste_2024-09-25_17-27-06" src="https://github.com/user-attachments/assets/ef00041d-08a5-4c11-b51a-4fab55f44348">

**Comment by Hiram-Wong** [comment]
仅支持在 electron 打开，不支持浏览器打开，因为深度融合了一些底层操作
