### ISSUE TITLE
最新版macos打开报错

### ISSUE THREAD

**Issue by kxcare** [Hiram-Wong/ZyPlayer#370]
### zyplayer 版本

3.3.9

### 重现步骤

打开即报错

### 报错信息

A JavaScript error occurred in the main process
Uncaught Exception:
Error: sonic boom is not ready yet
at SonicBoom.flushSync (/Applications/zyfun.app/Contents/Resources/app.asar/out/main/chunks/fastify-GGPgqnb_.js:9041:12)
at autoEnd (/Applications/zyfun.app/Contents/Resources/app.asar/out/main/chunks/fastify-GGPgqnb_.js:10294:13)
at callRefs (/Applications/zyfun.app/Contents/Resources/app.asar/out/main/chunks/fastify-GGPgqnb_.js:9283:8)
at process.onExit (/Applications/zyfun.app/Contents/Resources/app.asar/out/main/chunks/fastify-GGPgqnb_.js:9267:4)
at process.emit (node:events:518:28)
at App.<anonymous> (node:electron/js2c/browser_init:2:127161)
at App.emit (node:events:518:28)
at setup$1 (/Applications/zyfun.app/Contents/Resources/app.asar/out/main/index.js:82772:17)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async setup (/Applications/zyfun.app/Contents/Resources/app.asar/out/main/index.js:82810:3)

### 系统信息

macos12.7.6，m1芯片

**Comment by Hiram-Wong** [comment]
查看文档 https://zy.catni.cn/guide/usage.html#_1-3-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
