### ISSUE TITLE
[数据源] 存在资源站的API不支持

### ISSUE THREAD

**Issue by ACG-Q** [Hiram-Wong/ZyPlayer#388]
### zyplayer 版本

3.3.9

### 重现步骤

资源API来自于 [云解析资源网](https://www.yparse.com/help)，无论是XML格式API还是JSON格式API均无法获取资源成功

1. 在浏览器中直接访问，没有问题
2. 通过Postman进行访问也没有问题，不过如果Header中没有host的话，会导致400
3. 打开zyfun的调试功能，查看
GET请求: http://127.0.0.1:9978/api/v1/cms/home?sourceId=9cd592bc-9f38-47db-9d00-85c23cb5f723
Code: 500
返回信息:
```json
{
  "code": -1,
  "msg": "Internal Server Error - AxiosError",
  "data": "Request failed with status code 403"
}
```

### 报错信息

```
AxiosError: Request failed with status code 500
    at settle (file:///D:/Software/zyfun/resources/app.asar/out/renderer/assets/entry/index_B65CfWLC.js:4352:12)
    at XMLHttpRequest.onloadend (file:///D:/Software/zyfun/resources/app.asar/out/renderer/assets/entry/index_B65CfWLC.js:4657:7)
    at Axios.request (file:///D:/Software/zyfun/resources/app.asar/out/renderer/assets/entry/index_B65CfWLC.js:5198:41)
    at async request (file:///D:/Software/zyfun/resources/app.asar/out/renderer/assets/entry/index_B65CfWLC.js:5562:15)
    at async handleOpChange (file:///D:/Software/zyfun/resources/app.asar/out/renderer/assets/chunk/index_BU5_HHe2.js:661:23)
```

### 期望结果

正常获取资源

### 实际结果

无法正常获取

### 系统信息

 Windows/10.0

### 补充说明

另外，我希望能不能在 影视配置/添加 弹窗中添加一个选项

- [ ] 显示首页

> 是否显示“首页”这个分类选项卡, 默认勾选✔

**Comment by Hiram-Wong** [comment]
粗略看了一下是因为这个源不支持 ac=class方法

**Comment by Hiram-Wong** [comment]
要使用其他方式实现兼容性

**Comment by Hiram-Wong** [comment]
已修复，等开发版上传

**Comment by ACG-Q** [comment]
> 已修复，等开发版上传

老哥，速度呀👍👍👍👍
