### ISSUE TITLE
[播放器] 外部调用播放器的逻辑存在问题

### ISSUE THREAD

**Issue by ACG-Q** [Hiram-Wong/ZyPlayer#389]
### zyplayer 版本

3.3.9

### 重现步骤

1. 设置播放器为自定义，填写本地播放器地址D:\Portable\mpv-lazy\mpv.exe
2. 点击任意源的视频进行播放

- 推送成功
  ![image](https://github.com/user-attachments/assets/830e72c9-4846-4f2c-88fb-b72fc1747227)
- 推送失败
  ![image](https://github.com/user-attachments/assets/eca7dc63-023d-4c9a-882a-51fb95ccd76d)

### 报错信息

```
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at playHelper (file:///D:/Software/zyfun/resources/app.asar/out/renderer/assets/chunk/film_B1hF-ZR5.js:1919:23)
    at async callPlay (file:///D:/Software/zyfun/resources/app.asar/out/renderer/assets/chunk/Detail_D5FoIk04.js:189:24)
```

### 期望结果

可以正常播放

### 实际结果

存在部分网络视频无法正常调用外部播放器进行播放

### 系统信息

 Windows/10.0

### 补充说明

另外通过播放器手动调用，是可以正常播放【至于为什么上面填写的mpv，这里又用vlc？我不会用mpv💦】
![image](https://github.com/user-attachments/assets/46d226b4-4b62-4f0f-89cc-fa370a10337f)

**Comment by Hiram-Wong** [comment]
截图一下 设置里的第三方参数

**Comment by ACG-Q** [comment]
> 截图一下 设置里的第三方参数

填写的是"D:\Portable\mpv-lazy\mpv.exe"

![image](https://github.com/user-attachments/assets/e6da15d7-e96b-4aaf-ae54-eaaa5959515b)

**Comment by Hiram-Wong** [comment]
有复现方法吗，包括提供那个数据源数据

**Comment by ACG-Q** [comment]
1. 卧龙资源网
xml  https://collect.wolongzy.cc/api.php/provide/vod/at/xml/?ac=list
> 随便点击一个都是百分百复现

2. 新浪资源
xml  https://api.xinlangapi.com/xinlangapi.php/provide/vod/at/xml/ 
![image](https://github.com/user-attachments/assets/d0d29b8e-e193-4b1d-a27d-1315aed9967f)
> 选择xlm3u8没法推送成功，但是xlyun没有问题

**Comment by Hiram-Wong** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/21fa2ecc-ea1c-4260-b0f0-a67c4f331d0f" />

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/8edd7f81-7a5d-48c2-96b3-3fa4189240aa" />

均正常, 无法复现, 确认是不是最新开发版, t0xml 修复过一个播放问题，但是我忘了是否与这个相关

**Comment by ACG-Q** [comment]
是最新发布版
![image](https://github.com/user-attachments/assets/9309833c-c443-49ec-889d-1cadd78ebf35)
![image](https://github.com/user-attachments/assets/37e5effe-e933-4e66-a2c1-dfdc8a811fb9)

> 依旧报错

![image](https://github.com/user-attachments/assets/5f43718f-f1ec-46f5-b3c8-b0b40b29fc5f)
![image](https://github.com/user-attachments/assets/4db27d3a-fd0a-47dd-a27b-a255e24ccc95)

> 我拉取了仓库代码，确实在最新的代码中，该BUG已经被修复

![image](https://github.com/user-attachments/assets/f53b300e-8baa-4750-8df3-86366b68d4f3)
